### ISSUE TITLE
subrepticiously droping dimensions

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/2019-04-19_duke-data-dialogue#8]
I think the worst characteristic of drop behaviour in base R is that it not only drops the dimension you are subsetting on (which might be convenient some times), but also any other length one dimension that the array might have (which is error prone and rarely a desidered outcome : if the dimensions was there despite drop default beaviour it must be really wanted!!).
Perhaps it would be good to include some example of this to enforce the (already compelling enough) motivation for no drop behavior in rray. 
I dont know if this is what you had in mind in the "sumary: column selection" pages table, when in the last row you propose:
x[ , 1:2 , drop=T]
This only has effect if x has a lengh one first dimension

**Comment by DavisVaughan** [comment]
yea i know what you mean. it's a bit hard to convey that as quickly though, and my talk for useR is only 15 minutes 😢 it's definitely a compelling point though!
